### ISSUE TITLE
Add to awesome-dpsg list

### ISSUE THREAD

**Issue by mstoetzer** [TobiasMiosczka/NaMi#16]
Hi, ich möchte Dein Repo gerne in die awesome-dpsg Liste aufnehmen: https://github.com/mstoetzer/awesome-dpsg

**Comment by tobiasmiosczka** [comment]
Hallo Michael,

kannst Du gerne machen, kein Problem. 👍

Viele Grüße
Tobias

**Comment by mstoetzer** [comment]
Nice :) Gerne auch weiter verteilen und damit das eine schöne Liste wird
