### ISSUE TITLE
New Filter

### ISSUE THREAD

**Issue by matthiasholtkamp** [TobiasMiosczka/NaMi#2]
Ein zusätzlicher Filter um explizit nach Leitern (stufenübergreifend) zu filtern.

Zusätzlich wäre ein Filter für Biber toll.

------------------------------------------------------------------------------------
An additional filter to explicitly filter for Leaders (across levels).

Additionally, a filter for beavers would be great.

**Comment by tobiasmiosczka** [comment]
Filter für Biber implementiert. 
Da es zurzeit keinen einfachen Weg gibt  NaMi-API zu ermitteln, ob ein Mitglied ein Leiter ist, lässt sich dieses Feature noch nicht umsetzen.
